/* AUTO-GENERATED by scripts/gen_midi_catalog.py — do not edit. */
#ifndef MIDI_CATALOG_H
#define MIDI_CATALOG_H
#include <stdint.h>

typedef enum { GAME_INIT=0, GAME_DUNE2=1, GAME_MI=2, GAME_OTHER=3 } midi_game_t;
typedef struct { const char *title; const uint8_t *data; const uint8_t *data_end; midi_game_t game; int mi_idx; } midi_entry_t;
typedef struct { const char *title; uint32_t tick; } mi_section_t;

extern const uint8_t _binary_examples_mt32_rt_midi_Dune0_2_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_Dune0_2_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_Dune0_4_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_Dune0_4_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE10_17_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE10_17_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE11_18_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE11_18_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE12_19_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE12_19_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE13_20_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE13_20_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE14_21_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE14_21_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE15_22_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE15_22_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE16_23_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE16_23_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE16_24_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE16_24_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE17_21_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE17_21_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE18_24_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE18_24_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE19_21_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE19_21_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE19_22_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE19_22_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE19_23_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE19_23_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE1_3_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE1_3_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE1_4_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE1_4_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE1_5_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE1_5_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE1_6_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE1_6_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE1_7_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE1_7_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE20_22_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE20_22_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE2_8_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE2_8_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE3_9_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE3_9_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE4_10_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE4_10_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE5_11_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE5_11_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE6_12_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE6_12_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE7_10_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE7_10_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE7_11_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE7_11_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE7_13_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE7_13_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE7_9_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE7_9_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE8_10_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE8_10_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE8_11_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE8_11_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE9_13_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE9_13_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE9_14_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_DUNE9_14_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_Dune_init_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_Dune_init_mid_end[];
extern const uint8_t _binary_examples_mt32_rt_midi_MI_Complete_mid_start[];
extern const uint8_t _binary_examples_mt32_rt_midi_MI_Complete_mid_end[];

#define MI_SECTION_COUNT 13
static const mi_section_t MI_SECTIONS[] = {
    { "01 - Introduction", 0u },
    { "02 - The Scumm Bar", 237440u },
    { "03 - Mêlée Island", 332800u },
    { "04 - The Fettucini Brothers", 469920u },
    { "05 - Stalking the Shopkeeper", 599840u },
    { "06 - The Voodoo Lady", 723680u },
    { "07 - Searching For Treasure", 826560u },
    { "08 - The Journey", 955360u },
    { "09 - Monkey Island", 1063520u },
    { "10 - LeChuck", 1222720u },
    { "11 - Ghost Ship", 1365760u },
    { "12 - The Church", 1461280u },
    { "13 - Ending", 1614240u },
};

#define MIDI_COUNT 36
static const midi_entry_t MIDI_CATALOG[] = {
    { "Dune0_2", _binary_examples_mt32_rt_midi_Dune0_2_mid_start, _binary_examples_mt32_rt_midi_Dune0_2_mid_end, GAME_DUNE2, -1 },
    { "Dune0_4", _binary_examples_mt32_rt_midi_Dune0_4_mid_start, _binary_examples_mt32_rt_midi_Dune0_4_mid_end, GAME_DUNE2, -1 },
    { "DUNE10_17", _binary_examples_mt32_rt_midi_DUNE10_17_mid_start, _binary_examples_mt32_rt_midi_DUNE10_17_mid_end, GAME_DUNE2, -1 },
    { "DUNE11_18", _binary_examples_mt32_rt_midi_DUNE11_18_mid_start, _binary_examples_mt32_rt_midi_DUNE11_18_mid_end, GAME_DUNE2, -1 },
    { "DUNE12_19", _binary_examples_mt32_rt_midi_DUNE12_19_mid_start, _binary_examples_mt32_rt_midi_DUNE12_19_mid_end, GAME_DUNE2, -1 },
    { "DUNE13_20", _binary_examples_mt32_rt_midi_DUNE13_20_mid_start, _binary_examples_mt32_rt_midi_DUNE13_20_mid_end, GAME_DUNE2, -1 },
    { "DUNE14_21", _binary_examples_mt32_rt_midi_DUNE14_21_mid_start, _binary_examples_mt32_rt_midi_DUNE14_21_mid_end, GAME_DUNE2, -1 },
    { "DUNE15_22", _binary_examples_mt32_rt_midi_DUNE15_22_mid_start, _binary_examples_mt32_rt_midi_DUNE15_22_mid_end, GAME_DUNE2, -1 },
    { "DUNE16_23", _binary_examples_mt32_rt_midi_DUNE16_23_mid_start, _binary_examples_mt32_rt_midi_DUNE16_23_mid_end, GAME_DUNE2, -1 },
    { "DUNE16_24", _binary_examples_mt32_rt_midi_DUNE16_24_mid_start, _binary_examples_mt32_rt_midi_DUNE16_24_mid_end, GAME_DUNE2, -1 },
    { "DUNE17_21", _binary_examples_mt32_rt_midi_DUNE17_21_mid_start, _binary_examples_mt32_rt_midi_DUNE17_21_mid_end, GAME_DUNE2, -1 },
    { "DUNE18_24", _binary_examples_mt32_rt_midi_DUNE18_24_mid_start, _binary_examples_mt32_rt_midi_DUNE18_24_mid_end, GAME_DUNE2, -1 },
    { "DUNE19_21", _binary_examples_mt32_rt_midi_DUNE19_21_mid_start, _binary_examples_mt32_rt_midi_DUNE19_21_mid_end, GAME_DUNE2, -1 },
    { "DUNE19_22", _binary_examples_mt32_rt_midi_DUNE19_22_mid_start, _binary_examples_mt32_rt_midi_DUNE19_22_mid_end, GAME_DUNE2, -1 },
    { "DUNE19_23", _binary_examples_mt32_rt_midi_DUNE19_23_mid_start, _binary_examples_mt32_rt_midi_DUNE19_23_mid_end, GAME_DUNE2, -1 },
    { "DUNE1_3", _binary_examples_mt32_rt_midi_DUNE1_3_mid_start, _binary_examples_mt32_rt_midi_DUNE1_3_mid_end, GAME_DUNE2, -1 },
    { "DUNE1_4", _binary_examples_mt32_rt_midi_DUNE1_4_mid_start, _binary_examples_mt32_rt_midi_DUNE1_4_mid_end, GAME_DUNE2, -1 },
    { "DUNE1_5", _binary_examples_mt32_rt_midi_DUNE1_5_mid_start, _binary_examples_mt32_rt_midi_DUNE1_5_mid_end, GAME_DUNE2, -1 },
    { "DUNE1_6", _binary_examples_mt32_rt_midi_DUNE1_6_mid_start, _binary_examples_mt32_rt_midi_DUNE1_6_mid_end, GAME_DUNE2, -1 },
    { "DUNE1_7", _binary_examples_mt32_rt_midi_DUNE1_7_mid_start, _binary_examples_mt32_rt_midi_DUNE1_7_mid_end, GAME_DUNE2, -1 },
    { "DUNE20_22", _binary_examples_mt32_rt_midi_DUNE20_22_mid_start, _binary_examples_mt32_rt_midi_DUNE20_22_mid_end, GAME_DUNE2, -1 },
    { "DUNE2_8", _binary_examples_mt32_rt_midi_DUNE2_8_mid_start, _binary_examples_mt32_rt_midi_DUNE2_8_mid_end, GAME_DUNE2, -1 },
    { "DUNE3_9", _binary_examples_mt32_rt_midi_DUNE3_9_mid_start, _binary_examples_mt32_rt_midi_DUNE3_9_mid_end, GAME_DUNE2, -1 },
    { "DUNE4_10", _binary_examples_mt32_rt_midi_DUNE4_10_mid_start, _binary_examples_mt32_rt_midi_DUNE4_10_mid_end, GAME_DUNE2, -1 },
    { "DUNE5_11", _binary_examples_mt32_rt_midi_DUNE5_11_mid_start, _binary_examples_mt32_rt_midi_DUNE5_11_mid_end, GAME_DUNE2, -1 },
    { "DUNE6_12", _binary_examples_mt32_rt_midi_DUNE6_12_mid_start, _binary_examples_mt32_rt_midi_DUNE6_12_mid_end, GAME_DUNE2, -1 },
    { "DUNE7_10", _binary_examples_mt32_rt_midi_DUNE7_10_mid_start, _binary_examples_mt32_rt_midi_DUNE7_10_mid_end, GAME_DUNE2, -1 },
    { "DUNE7_11", _binary_examples_mt32_rt_midi_DUNE7_11_mid_start, _binary_examples_mt32_rt_midi_DUNE7_11_mid_end, GAME_DUNE2, -1 },
    { "DUNE7_13", _binary_examples_mt32_rt_midi_DUNE7_13_mid_start, _binary_examples_mt32_rt_midi_DUNE7_13_mid_end, GAME_DUNE2, -1 },
    { "DUNE7_9", _binary_examples_mt32_rt_midi_DUNE7_9_mid_start, _binary_examples_mt32_rt_midi_DUNE7_9_mid_end, GAME_DUNE2, -1 },
    { "DUNE8_10", _binary_examples_mt32_rt_midi_DUNE8_10_mid_start, _binary_examples_mt32_rt_midi_DUNE8_10_mid_end, GAME_DUNE2, -1 },
    { "DUNE8_11", _binary_examples_mt32_rt_midi_DUNE8_11_mid_start, _binary_examples_mt32_rt_midi_DUNE8_11_mid_end, GAME_DUNE2, -1 },
    { "DUNE9_13", _binary_examples_mt32_rt_midi_DUNE9_13_mid_start, _binary_examples_mt32_rt_midi_DUNE9_13_mid_end, GAME_DUNE2, -1 },
    { "DUNE9_14", _binary_examples_mt32_rt_midi_DUNE9_14_mid_start, _binary_examples_mt32_rt_midi_DUNE9_14_mid_end, GAME_DUNE2, -1 },
    { "Dune_init", _binary_examples_mt32_rt_midi_Dune_init_mid_start, _binary_examples_mt32_rt_midi_Dune_init_mid_end, GAME_INIT, -1 },
    { "MI_Complete", _binary_examples_mt32_rt_midi_MI_Complete_mid_start, _binary_examples_mt32_rt_midi_MI_Complete_mid_end, GAME_MI, 0 },
};

#endif /* MIDI_CATALOG_H */