#!/usr/bin/env python3
"""
Generate examples/mt32_rt/midi_catalog.h from examples/mt32_rt/midi/*.mid

Catalog entries:
  - Each .mid becomes one song entry.
  - Game = DUNE2 for DUNE*.mid / Dune*.mid, MI for MI_Complete.mid, INIT for Dune_init.mid.
  - For MI_Complete, also emits a section table parsed from track-0 Marker meta-events,
    so the UI can sub-navigate it by scene.

Symbol names follow objcopy's convention:
  _binary_examples_mt32_rt_midi_<sanitized>_mid_start / _end
  (objcopy replaces every non-alphanum path char with '_')
"""
import os, re, struct, sys, pathlib

MIDI_DIR = pathlib.Path("examples/mt32_rt/midi")
OUT = pathlib.Path("examples/mt32_rt/midi_catalog.h")

def sym(path):
    # objcopy turns path chars that aren't [A-Za-z0-9] into '_'
    return "_binary_" + re.sub(r'[^A-Za-z0-9]', '_', str(path))

def vlq(d, p):
    v = 0
    while True:
        b = d[p]; p += 1; v = (v << 7) | (b & 0x7F)
        if not (b & 0x80):
            return v, p

def parse_markers(path):
    """Return list of (tick, title) for Marker (FF 06) events in track 0."""
    with open(path, "rb") as f:
        d = f.read()
    if d[:4] != b"MThd":
        return []
    fmt, ntrk, div = struct.unpack(">HHH", d[8:14])
    out = []
    p = 14
    if d[p:p+4] != b"MTrk":
        return []
    tl = struct.unpack(">I", d[p+4:p+8])[0]
    start = p + 8; end = start + tl; q = start
    tick = 0; running = 0
    while q < end:
        dt, q = vlq(d, q); tick += dt
        b = d[q]
        if b == 0xFF:
            mt = d[q+1]; ml, q2 = vlq(d, q+2); data = d[q2:q2+ml]; q = q2 + ml
            if mt == 0x06:  # Marker
                try: s = data.decode("latin1").strip()
                except Exception: s = ""
                if s: out.append((tick, s))
        elif b == 0xF0 or b == 0xF7:
            ml, q2 = vlq(d, q+1); q = q2 + ml
        else:
            if b & 0x80:
                running = b; q += 1
            st = running
            if 0xC0 <= st < 0xE0: q += 1
            else: q += 2
    return out

def classify(name):
    n = name.lower()
    if n == "dune_init.mid": return "GAME_INIT"
    if n.startswith("dune"):  return "GAME_DUNE2"
    if n == "mi_complete.mid": return "GAME_MI"
    return "GAME_OTHER"

def pretty(name):
    return name[:-4] if name.lower().endswith(".mid") else name

def main():
    files = sorted(MIDI_DIR.glob("*.mid"), key=lambda p: (classify(p.name), p.name.lower()))
    if not files:
        print(f"no .mid files under {MIDI_DIR}", file=sys.stderr)
        sys.exit(1)

    lines = []
    lines.append("/* AUTO-GENERATED by scripts/gen_midi_catalog.py — do not edit. */")
    lines.append("#ifndef MIDI_CATALOG_H")
    lines.append("#define MIDI_CATALOG_H")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("typedef enum { GAME_INIT=0, GAME_DUNE2=1, GAME_MI=2, GAME_OTHER=3 } midi_game_t;")
    lines.append("typedef struct { const char *title; const uint8_t *data; const uint8_t *data_end; midi_game_t game; int mi_idx; } midi_entry_t;")
    lines.append("typedef struct { const char *title; uint32_t tick; } mi_section_t;")
    lines.append("")

    # externs — objcopy -I binary generates _binary_<sanitized_path>_start / _end
    for p in files:
        s = sym(p)
        lines.append(f"extern const uint8_t {s}_start[];")
        lines.append(f"extern const uint8_t {s}_end[];")
    lines.append("")

    # MI sections (parsed from track 0 markers of MI_Complete.mid, if present)
    mi_entry = next((p for p in files if p.name == "MI_Complete.mid"), None)
    mi_sections = parse_markers(mi_entry) if mi_entry else []
    lines.append(f"#define MI_SECTION_COUNT {len(mi_sections)}")
    lines.append("static const mi_section_t MI_SECTIONS[] = {")
    for tick, title in mi_sections:
        esc = title.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    {{ "{esc}", {tick}u }},')
    if not mi_sections:
        lines.append('    { "(full)", 0u },')
    lines.append("};")
    lines.append("")

    # catalog
    lines.append(f"#define MIDI_COUNT {len(files)}")
    lines.append("static const midi_entry_t MIDI_CATALOG[] = {")
    mi_idx_counter = 0
    for p in files:
        s = sym(p)
        g = classify(p.name)
        title = pretty(p.name)
        mi_idx = -1
        if g == "GAME_MI":
            mi_idx = 0  # the MI file supports section navigation
        lines.append(f'    {{ "{title}", {s}_start, {s}_end, {g}, {mi_idx} }},')
    lines.append("};")
    lines.append("")
    lines.append("#endif /* MIDI_CATALOG_H */")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} — {len(files)} entries, {len(mi_sections)} MI sections")

if __name__ == "__main__":
    main()
