#!/usr/bin/env python3
"""
Embed every .lua and .sms file under examples/war1/scripts/ as a raw blob +
generate a C catalog mapping "scripts/<relpath>" → {blob_ptr, size}.
.sms files are campaign map data (plain Lua text with Player/Unit/Tile calls)
so they're embedded the same way as scripts.

Called from Makefile. Emits:
    examples/war1/war1_script_catalog.h  (C header with extern decls + table)

The objcopy step happens separately in the Makefile (one rule per .lua →
per-file .o), so all we do here is (a) enumerate the files in a stable order
and (b) emit the C-accessible catalog linking the objcopy-generated symbols
to their filename strings.
"""
import pathlib, re, sys

SCRIPTS = pathlib.Path("examples/war1/scripts")
OUT_HDR = pathlib.Path("examples/war1/war1_script_catalog.h")

def sym(path_rel: str) -> str:
    # objcopy -I binary names its symbols after the path with non-alphanum→_.
    # Our Makefile objcopies each .lua at examples/war1/scripts/<rel>, so the
    # symbol is _binary_examples_war1_scripts_<rel sanitized>_start / _end.
    flat = re.sub(r"[^A-Za-z0-9]", "_", f"examples/war1/scripts/{path_rel}")
    return f"_binary_{flat}"

def main():
    files = sorted(p.relative_to(SCRIPTS).as_posix()
                   for p in (list(SCRIPTS.rglob("*.lua"))
                             + list(SCRIPTS.rglob("*.sms"))
                             + list(SCRIPTS.rglob("*.smp"))
                             + list(SCRIPTS.rglob("*.txt"))))
    if not files:
        print("no .lua/.sms/.smp files under examples/war1/scripts/", file=sys.stderr)
        sys.exit(1)

    lines = []
    lines.append("/* AUTO-GENERATED by scripts/war1_embed_lua.py — do not edit. */")
    lines.append("#pragma once")
    lines.append("#include <stddef.h>")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append('extern "C" {')
    lines.append("#endif")
    lines.append("")
    for rel in files:
        s = sym(rel)
        lines.append(f"extern const uint8_t {s}_start[];")
        lines.append(f"extern const uint8_t {s}_end[];")
    lines.append("")
    lines.append("typedef struct { const char *path; const uint8_t *data; const uint8_t *data_end; } war1_script_entry_t;")
    lines.append("")
    lines.append(f"#define WAR1_SCRIPT_COUNT {len(files)}")
    lines.append("static const war1_script_entry_t WAR1_SCRIPTS[] = {")
    for rel in files:
        s = sym(rel)
        # Stratagus typically calls Load("scripts/..."), so we store paths
        # both with the scripts/ prefix AND the bare form. The open lookup
        # can match whichever shape the caller uses.
        lines.append(f'    {{ "scripts/{rel}", {s}_start, {s}_end }},')
    lines.append("};")
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")

    OUT_HDR.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT_HDR} with {len(files)} script entries")

if __name__ == "__main__":
    main()
